/*
 * effect_sprites.h - Visual effect sprite data for Bass Hole
 *
 * Contains RGB565 sprite data for bubbles, sparkles, splash effects.
 * Generated by img2code.py from assets/resized/effects/
 *
 * Effects are rendered at 16x16 pixels.
 * Transparency color: 0xF81F (magenta)
 */

#ifndef EFFECT_SPRITES_H
#define EFFECT_SPRITES_H

#include <Arduino.h>

// ============================================================================
// BUBBLE SPRITES
// ============================================================================

#define SPRITE_BUBBLE_SM_WIDTH  16
#define SPRITE_BUBBLE_SM_HEIGHT 16

extern const uint16_t sprite_bubble_sm[] PROGMEM;

#define SPRITE_BUBBLE_MED_WIDTH  16
#define SPRITE_BUBBLE_MED_HEIGHT 16

extern const uint16_t sprite_bubble_med[] PROGMEM;

// ============================================================================
// EFFECT SPRITES
// ============================================================================

#define SPRITE_SPLASH_WIDTH  16
#define SPRITE_SPLASH_HEIGHT 16

extern const uint16_t sprite_splash[] PROGMEM;

#define SPRITE_SPARKLE_WIDTH  16
#define SPRITE_SPARKLE_HEIGHT 16

extern const uint16_t sprite_sparkle[] PROGMEM;

#define SPRITE_EXPLOSION_WIDTH  16
#define SPRITE_EXPLOSION_HEIGHT 16

extern const uint16_t sprite_explosion[] PROGMEM;

#endif // EFFECT_SPRITES_H
