/*
 * fish_sprites.h - Fish sprite data for Bass Hole
 *
 * Contains RGB565 sprite data for all fish species.
 * Generated by img2code.py from assets/resized/fish/
 *
 * Fish are rendered at 32x32 pixels (or aspect-adjusted height).
 * Transparency color: 0xF81F (magenta)
 */

#ifndef FISH_SPRITES_H
#define FISH_SPRITES_H

#include <Arduino.h>

// ============================================================================
// ACTUAL SPRITE DATA
// ============================================================================

// Include the actual sprite pixel data
#include "fish_r_trout_data.h"

// ============================================================================
// FISH SPRITE DECLARATIONS (for other fish - placeholders until converted)
// ============================================================================

// Bluegill - Fast breeder, low value
#define SPRITE_FISH_BLUEGILL_WIDTH  32
#define SPRITE_FISH_BLUEGILL_HEIGHT 32

extern const uint16_t sprite_fish_bluegill[] PROGMEM;

// Smallmouth Bass - Mid-tier
#define SPRITE_FISH_SMALLMOUTH_WIDTH  32
#define SPRITE_FISH_SMALLMOUTH_HEIGHT 32

extern const uint16_t sprite_fish_smallmouth[] PROGMEM;

// Channel Catfish - Slow, high value
#define SPRITE_FISH_CHANNEL_CAT_WIDTH  32
#define SPRITE_FISH_CHANNEL_CAT_HEIGHT 32

extern const uint16_t sprite_fish_channel_cat[] PROGMEM;

// Largemouth Bass - Ty's species, premium
#define SPRITE_FISH_L_BASS_WIDTH  32
#define SPRITE_FISH_L_BASS_HEIGHT 32

extern const uint16_t sprite_fish_l_bass[] PROGMEM;

// Kokanee Salmon - Seasonal bonuses
#define SPRITE_FISH_KOKANEE_WIDTH  32
#define SPRITE_FISH_KOKANEE_HEIGHT 32

extern const uint16_t sprite_fish_kokanee[] PROGMEM;

// Steelhead Trout - Speed + value hybrid
#define SPRITE_FISH_STEELHEAD_WIDTH  32
#define SPRITE_FISH_STEELHEAD_HEIGHT 32

extern const uint16_t sprite_fish_steelhead[] PROGMEM;

// Striped Bass - Tank fish
#define SPRITE_FISH_STRIPED_BASS_WIDTH  32
#define SPRITE_FISH_STRIPED_BASS_HEIGHT 32

extern const uint16_t sprite_fish_striped_bass[] PROGMEM;

// Sacramento Pikeminnow - Invasive (negative value)
#define SPRITE_FISH_PIKEMINNOW_WIDTH  32
#define SPRITE_FISH_PIKEMINNOW_HEIGHT 32

extern const uint16_t sprite_fish_pikeminnow[] PROGMEM;

// Sturgeon - Ultra rare
#define SPRITE_FISH_STURGEON_WIDTH  32
#define SPRITE_FISH_STURGEON_HEIGHT 32

extern const uint16_t sprite_fish_sturgeon[] PROGMEM;

// ============================================================================
// FISH SPRITE LOOKUP
// ============================================================================

// Array of fish sprite pointers indexed by FishSpecies enum
// Defined in fish_sprites.cpp
extern const uint16_t* const FISH_SPRITES[];
extern const uint8_t FISH_SPRITE_WIDTHS[];
extern const uint8_t FISH_SPRITE_HEIGHTS[];

#endif // FISH_SPRITES_H
