/*
 * ui_sprites.h - UI element sprite data for Bass Hole
 *
 * Contains RGB565 sprite data for coins, pellets, hearts, buttons.
 * Generated by img2code.py from assets/resized/ui/
 *
 * UI elements are rendered at 16x16 pixels.
 * Transparency color: 0xF81F (magenta)
 */

#ifndef UI_SPRITES_H
#define UI_SPRITES_H

#include <Arduino.h>

// ============================================================================
// COIN SPRITES
// ============================================================================

#define SPRITE_COIN_GOLD_WIDTH  16
#define SPRITE_COIN_GOLD_HEIGHT 16

extern const uint16_t sprite_coin_gold[] PROGMEM;

#define SPRITE_COIN_SILVER_WIDTH  16
#define SPRITE_COIN_SILVER_HEIGHT 16

extern const uint16_t sprite_coin_silver[] PROGMEM;

// ============================================================================
// FOOD SPRITES
// ============================================================================

#define SPRITE_PELLET_WIDTH  16
#define SPRITE_PELLET_HEIGHT 16

extern const uint16_t sprite_pellet[] PROGMEM;

// ============================================================================
// HEART SPRITES (for hunger/health display)
// ============================================================================

#define SPRITE_HEART_FULL_WIDTH  16
#define SPRITE_HEART_FULL_HEIGHT 16

extern const uint16_t sprite_heart_full[] PROGMEM;

#define SPRITE_HEART_EMPTY_WIDTH  16
#define SPRITE_HEART_EMPTY_HEIGHT 16

extern const uint16_t sprite_heart_empty[] PROGMEM;

// ============================================================================
// BUTTON SPRITES
// ============================================================================

#define SPRITE_BUTTON_BUY_WIDTH  16
#define SPRITE_BUTTON_BUY_HEIGHT 16

extern const uint16_t sprite_button_buy[] PROGMEM;

#define SPRITE_BUTTON_UPGRADE_WIDTH  16
#define SPRITE_BUTTON_UPGRADE_HEIGHT 16

extern const uint16_t sprite_button_upgrade[] PROGMEM;

#endif // UI_SPRITES_H
