#!/usr/bin/env python3
"""
img2code.py - Convert images to C arrays for ESP32 TFT displays

Converts PNG/JPG images to RGB565 format C arrays that can be included
directly in Arduino sketches and rendered with TFT_eSPI pushImage().

Usage:
    python img2code.py input.png --name sprite_name --output sprite.h
    python img2code.py input.png  # Uses input filename as name, outputs to stdout

Requirements:
    pip install Pillow

Output format:
    RGB565 (16-bit color: 5 bits red, 6 bits green, 5 bits blue)
"""

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow library required. Install with: pip install Pillow")
    sys.exit(1)


def rgb_to_rgb565(r, g, b):
    """Convert 8-bit RGB to 16-bit RGB565."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert_image(input_path, name=None, transparent_color=None):
    """
    Convert image to RGB565 C array.

    Args:
        input_path: Path to input image
        name: Name for the C array (defaults to filename)
        transparent_color: RGB tuple for transparency (optional)

    Returns:
        Tuple of (header_string, width, height)
    """
    img = Image.open(input_path)

    # Convert to RGBA to handle transparency
    if img.mode != 'RGBA':
        img = img.convert('RGBA')

    width, height = img.size
    pixels = list(img.getdata())

    # Generate array name from filename if not provided
    if name is None:
        name = Path(input_path).stem
        # Make C-safe: replace non-alphanumeric with underscore
        name = ''.join(c if c.isalnum() else '_' for c in name)
        name = f"sprite_{name}"

    # Build the C header
    lines = []
    lines.append(f"// {Path(input_path).name} - Auto-generated sprite data")
    lines.append(f"// Generated by img2code.py")
    lines.append(f"// Size: {width}x{height} pixels, {width * height * 2} bytes")
    lines.append("")
    lines.append(f"#ifndef {name.upper()}_H")
    lines.append(f"#define {name.upper()}_H")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append(f"#define {name.upper()}_WIDTH  {width}")
    lines.append(f"#define {name.upper()}_HEIGHT {height}")
    lines.append("")

    # Determine if we need transparency
    has_alpha = any(p[3] < 128 for p in pixels)

    if has_alpha:
        lines.append(f"// Transparency color (magenta): 0xF81F")
        lines.append(f"#define {name.upper()}_TRANSPARENT 0xF81F")
        lines.append("")

    lines.append(f"const uint16_t {name}[{width * height}] PROGMEM = {{")

    # Convert pixels
    pixel_values = []
    for i, pixel in enumerate(pixels):
        r, g, b, a = pixel

        # Handle transparency (use magenta as transparent color)
        if a < 128:
            rgb565 = 0xF81F  # Magenta
        else:
            rgb565 = rgb_to_rgb565(r, g, b)

        pixel_values.append(f"0x{rgb565:04X}")

    # Format as rows matching image width
    row_size = 8  # Values per line in output
    for i in range(0, len(pixel_values), row_size):
        row = pixel_values[i:i + row_size]
        prefix = "    "
        suffix = "," if i + row_size < len(pixel_values) else ""
        lines.append(f"{prefix}{', '.join(row)}{suffix}")

    lines.append("};")
    lines.append("")
    lines.append(f"#endif // {name.upper()}_H")
    lines.append("")

    return '\n'.join(lines), width, height


def main():
    parser = argparse.ArgumentParser(
        description='Convert images to C arrays for ESP32 TFT displays',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python img2code.py fish.png --name sprite_trout --output trout.h
    python img2code.py fish.png > fish.h
    python img2code.py *.png --output-dir sprites/

The output is RGB565 format compatible with TFT_eSPI pushImage().
Transparent pixels (alpha < 128) are converted to magenta (0xF81F).
        """
    )
    parser.add_argument('input', help='Input image file (PNG, JPG, etc.)')
    parser.add_argument('--name', '-n', help='C array name (default: sprite_<filename>)')
    parser.add_argument('--output', '-o', help='Output file (default: stdout)')
    parser.add_argument('--quiet', '-q', action='store_true', help='Suppress info messages')

    args = parser.parse_args()

    # Check input exists
    if not Path(args.input).exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    # Convert
    try:
        result, width, height = convert_image(args.input, args.name)
    except Exception as e:
        print(f"Error converting image: {e}", file=sys.stderr)
        sys.exit(1)

    # Output
    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, 'w') as f:
            f.write(result)
        if not args.quiet:
            print(f"Converted {args.input} ({width}x{height}) -> {args.output}", file=sys.stderr)
    else:
        print(result)
        if not args.quiet:
            print(f"// Converted {args.input} ({width}x{height})", file=sys.stderr)


if __name__ == '__main__':
    main()
